### ISSUE TITLE
Email send issue - BE

### ISSUE THREAD

**Issue by RadhikaPPatel** [MediaMash/buildly-core#5]
- [ ] A number of emails did not make it to the desired email inbox.  From what we can tell at least the iCloud or apple hosted email was not receiving our email.  We also noticed that at least one Microsoft Outlook account had to search in the SPAM folder to find it.

**Comment by ashishkmishra36** [comment]
The issue lies with the free tier IP's  that SENDGRID uses for sending the email.Will be solved when we upgrade our plan or switch to a different email provider.
